# Cargo.toml (rust-shark-core)

# ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
# package
# ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
[package]
name = "rust-shark-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

# ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
# dependencies
# ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
[dependencies]
pcap.workspace = true
crossbeam-channel.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
lru.workspace = true
chrono.workspace = true
nom.workspace = true
md-5.workspace = true
sha2.workspace = true
rusqlite.workspace = true
maxminddb.workspace = true
dirs.workspace = true

# ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
# target
# ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
[target.'cfg(unix)'.dependencies]
libc.workspace = true

[dev-dependencies]
tempfile.workspace = true
